##
## EPITECH PROJECT, 2017
## PSU_2018_malloc
## File description:
## Makefile
##

SRC	=

OBJ	=	$(SRC:.cpp=.o)

NAME	=	pbrain-gomoku-ai

CFLAGS	=	-Wall -Wextra

all:	
	cp pbrain-gomoku-ai.py $(NAME)
	chmod +x pbrain-gomoku-ai

clean:
	rm pbrain-gomoku-ai

fclean: clean


re: all

.PHONY: all clean re fclean
